# Generated by Django 2.2.4 on 2022-06-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220626_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDesc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Description'),
        ),
    ]
