# Generated by Django 2.2.4 on 2022-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite_Book_app', '0002_auto_20220629_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='A history of the universe'),
            preserve_default=False,
        ),
    ]
