# Generated by Django 2.2.4 on 2022-06-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favorite_Book_app', '0003_book_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liked_by',
            new_name='users_who_like',
        ),
    ]
