# Generated by Django 2.2.4 on 2022-06-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
