# Generated by Django 2.2.4 on 2022-06-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_book_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
    ]
