# Generated by Django 2.2.4 on 2022-06-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20220621_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.CharField(max_length=20),
        ),
    ]
