# Generated by Django 2.2.4 on 2022-06-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_remove_book_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
