# Generated by Django 2.2.4 on 2022-06-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_book_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
