# Generated by Django 2.2.4 on 2022-06-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=8)),
                ('firstname', models.CharField(max_length=8)),
                ('lastname', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
